### ISSUE TITLE
mark tests requiring internet

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#105]
It looks like `test_deps_install_command`, 'test_deps_licenses_command', 'test_deps_outdated_command_file' and many other tests require internet access, which isnt possible in an rpmbuild.

Ideally the test suite marks these tests with a pytest marker so they can be easily de-selected.  Often the marker is called 'network'.

**Comment by jayvdb** [comment]
To workaround this I included the following in the [.spec](https://build.opensuse.org/package/view_file/home:jayvdb:dephell/python-dephell/python-dephell.spec?expand=1) , which includes removal of safety tests as well.
```sh
rm \
  tests/test_commands/test_deps_outdated.py \
  tests/test_commands/test_deps_install.py \
  tests/test_commands/test_deps_licenses.py \
  tests/test_commands/test_deps_tree.py \
  tests/test_commands/test_generate_license.py \
  tests/test_commands/test_inspect_venv.py \
  tests/test_commands/test_jail_install.py \
  tests/test_commands/test_package_downloads.py \
  tests/test_commands/test_package_install.py \
  tests/test_commands/test_package_search.py \
  tests/test_commands/test_package_show.py \
  tests/test_controllers/test_safety.py \
  tests/test_controllers/test_snyk.py \
  tests/test_converters/test_imports.py \
  tests/test_repositories/test_conda.py \
  tests/test_repositories/test_warehouse.py \
  tests/test_resolving/test_smoke.py
```

Submitted at https://build.opensuse.org/request/show/704108 ; thx so much for very prompt resolution to the various issues so that packaging was painless.

**Comment by orsinium** [comment]
Right, most of the tests depend on the network (or cache as well).

**Comment by orsinium** [comment]
From the next release you can use `--no-network` to run only offline tests. Example:
https://travis-ci.org/dephell/dephell/jobs/544658821
Thank you for the issue :heart:

**Comment by jayvdb** [comment]
@orsinium much appreciated; I left a note at https://github.com/dephell/dephell/pull/149/files#r292890208
