### ISSUE TITLE
Try to get author from `from` in `generate license`

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#107]
Author detection logic:

1. Config option `--owner` (#104)
1. Git tag

New logic: 

1. Config option `--owner` (#104)
1. Read `from` dependencies file to get authors.
1. `from python_discover import Root as PackageRoot; PackageRoot(self.config['project']).metainfo.authors`.
1. Git tag

**Comment by nandahkrishna** [comment]
So this issue would require parsing the config file indicated in the `build_from` parser as `--from`, getting the author metadata from that and accordingly setting that as author name in license - is this right?

**Comment by orsinium** [comment]
Yeah, right.
loader = CONVERTERS[self.config['from']['format']]
root = loader.load(...)
if root.authors:
...

**Comment by nandahkrishna** [comment]
Alright, thanks.
