### ISSUE TITLE
Autocomplete does not quote path on macOS

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#111]
I ran `dephell autocomplete` and in my `~/.zshrc` it added the line `source /Users/dylan/Library/Application Support/dephell/_dephell_zsh_autocomplete`.  The space in the path breaks it.  Solution is just to add quotes around the path which I did manually for now.

Using dephell 0.7.3 on macOS 10.14.5 with zsh 5.7.1.

**Comment by orsinium** [comment]
Thank you for an issue :) Do you want to make Pull Request for it? Just fix it in `dephell/commands/autocomple.py`
