### ISSUE TITLE
Install prereleases to jail

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#113]
Jail is a super cool feature for testing out new packages in an isolated environment.  I'd really like to be able to install prerelease packages there for testing, is there already a way to do this?  If not, could it be added?

**Comment by orsinium** [comment]
Almost there. Dephell support it, I've just forgot enable `--pre` key for jail :) We need to add `builders.build_resolver(parser)` in [jail_install.py](https://github.com/dephell/dephell/blob/master/dephell/commands/jail_install.py#L32)

**Comment by orsinium** [comment]
Do you want to contribute it as well?
