### ISSUE TITLE
Help option for commands

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#119]
Sorry if this is already covered somewhere, I couldn’t find it if so.  Would it be feasible to add a —help or similar option to each individual command?  There is some really great documentation for each command, it would be nice to be able to access these (or similar) descriptions while using the tool so I don’t have to keep the website open for searching.

Example of what I’d like to see:
```
$ dephell deps convert —help

Convert dependencies between formats.
Options:
—from : Format or path to convert from
—to: Format or path to convert to
—from-format: Format to convert from
..etc

Available formats:
- pip
- poetry
- pipenv
```

Obviously that’s a lot to add for every command, so maybe the goal should be to generate these from the docs?  Or generate part of the docs from the descriptions?  Just to make it easier to maintain.  An easier solution would just be to display the docstring which has the link to the full docs.

I think the way to do this with ArgParser is to use [parent parsers](https://docs.python.org/3/library/argparse.html#parents) so each sub command gets its own -h/—help option.

**Comment by orsinium** [comment]
> An easier solution would just be to display the docstring which has the link to the full docs.

This is exactly how it works now :) Just docstrings contain only short description and link on the docs.

```
❯deps convert --help
usage: dephell deps convert [-h] [-c CONFIG] [-e ENV] [--from FROM]
...

Convert dependencies between formats.
https://dephell.readthedocs.io/en/latest/cmd-deps-convert.html

optional arguments:
  -h, --help            show this help message and exit
...
```

However, I understand your point. It would be nice to provide some quick examples for each command here.

**Comment by dbanty** [comment]
Huh, I could have sworn I tried that and didn’t see all the helpful help content.  Maybe I’d typed something wrong because of course now I see it just fine :P.  Well it seems yet again you’ve thought of everything!

**Comment by orsinium** [comment]
Maybe, we have to simplify "usage" string :thinking:

**Comment by dbanty** [comment]
Maybe, there is a lot there.  Could try to decide on what the most basic case is for each command and just show that in usage.  In the case of convert that'd be something like `dephell deps convert --from FROM --to TO` right?

Another thing that I think would help is to modify the message which prints out when you type something wrong.  Right now it shows all the possible commands in an unformatted blob, I think it's just the default behavior of argparse when it sees an unknown command.  Would be better to show the default help message (`dephell --help`), though I don't know how to override the argparse behavior.  Maybe using [parse_known_args](https://docs.python.org/dev/library/argparse.html#partial-parsing) instead of parse_args in cli.py?  Then if anything comes up as unknown you can call --help like you already are?

I haven't done much experimenting, just spit balling while reading through pieces of the code :).

**Comment by orsinium** [comment]
I've split this conversation by 3 different issues to make the context more clear.
