### ISSUE TITLE
Simplify "usage" for commands

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#120]
Now, argparse outputs really long and ugly `usage` for `--help`. We can replace `formatter.add_usage(...)` call by the custom implementation to make it nicer. I think it should look like this:

```
usage: dephell project bump [flags] name
```

i.e. replace all flags with `[flags]`

See #119 for context.

## How

For every command explicitly specify usage like this:

```python
parser = ArgumentParser(
    prog='dephell project bump',
    description=cls.__doc__,
    usage='dephell project bump [flags] rule_name',
)
```

This is a repetition of the same pattern, but explicit. Let's keep it simple, without introspection and magic.

**Comment by skullsai** [comment]
Hey, I am looking to contribute to this project. However, I haven't worked on any issues before. I  came across this issue and I would very much like to help fix it. Could I please be assigned to this issue?

**Comment by orsinium** [comment]
Welcome! I can't assign issues on someone who's not in organization. I'll just add tag WIP. So, feel free to work on it. Thank you :)

**Comment by orsinium** [comment]
[CONTRIBUTING.md](https://github.com/dephell/dephell/blob/master/CONTRIBUTING.md) was added in #146, it can help you with start.

**Comment by orsinium** [comment]
@skullsay, how is it going? Do you have any questions?
