### ISSUE TITLE
Try to predict command

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#122]
1. If one word passed as a command, but there is no command with this name, it is possible that missed the first word. For example, if called command `shell` it means `venv shell`. 
1. If command not found, possibly it's a misspelling. For exapmle, `venv shll` means `venv shell`. There is the simplest way to do it:

```python
from collections import Counter

def similar(command1: str, command2: str) -> bool:
  c1 = Counter(command1)
  c2 = Counter(command2)
  c = (c1 - c2) + (c2 - c1)
  diff = sum(c.values())
  return diff < 2
```

See #119 for context.

**Comment by sanv00** [comment]
Hey, I am looking to contribute to this project. However, I haven't worked on any issues before. I came across this issue and I would very much like to help fix it. Could I please be assigned to this issue?

**Comment by orsinium** [comment]
Thank you! I've labeled it as WIP for you. Good look :)
