### ISSUE TITLE
Windows character encoding issue when using `dephell generate authors` in the pypa sampleproject

### ISSUE THREAD

**Issue by rwalton00** [dephell/dephell#124]
On Windows I see the following traceback when issuing the `dephell generate authors` command in the pypa sampleproject root directory,

```
Traceback (most recent call last):
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\Scripts\dephell-script.py", line 11, in <module>
    load_entry_point('dephell', 'console_scripts', 'dephell')()
  File "c:\users\rob\documents\projects\dephell\dephell\cli.py", line 95, in entrypoint
    exit(main(argv[1:]))
  File "c:\users\rob\documents\projects\dephell\dephell\cli.py", line 77, in main
    result = task()
  File "c:\users\rob\documents\projects\dephell\dephell\commands\generate_authors.py", line 40, in __call__
    Path('AUTHORS').write_text('\n'.join(sorted(lines)))
  File "C:\Users\Rob\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1209, in write_text
    return f.write(data)
  File "C:\Users\Rob\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
```

The fix is to set the encoding to `utf-16` in the `Path.write_text` call in `generate_authors.py`.

**Comment by rwalton00** [comment]
I can prepare a PR for this fix. Can I push directly to a branch here or would you rather I forked the repo?

**Comment by orsinium** [comment]
1. Wow, you've run DepHell on Windows. DepHell isn't tested on Windows yet (see #110, #67, #77). Could you also get dev version of dephell, run tests for it and make an issue with pytest output. It would be a great start to implement windows support.
1. Why `utf-16`, not `utf-8`? I'm not an expert in encodings, just utf-8 always worked to me :)
1. Make PR as you want, it doesn't matter to me at all.

**Comment by orsinium** [comment]
Thank you for an issue :)

**Comment by rwalton00** [comment]
Actually, that was a typo; you're right, it should be `utf-8`. That will work fine for the characters causing the issue.

I'm trying out `dephell` on Windows in the hope of contributing to the project and helping to implement Windows support. Now I have it up and running since you fixed my installation issue (thanks for that!) I can start to fix some of these errors I'm seeing. I'll post up issues as I run into them.

There are also quite a few test failures I haven't investigated yet. Will look into those also.
