### ISSUE TITLE
Document the VCS functionality of project bump

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#130]
I used dephell project bump today and was surprised to found that it created a Git commit and tag for me.  That's a useful feature, but I wasn't quite ready to commit yet.  We should add to the docs that it does this so as to not catch others by surprise.

**Comment by orsinium** [comment]
Implemented in #114, will be in next release.

**Comment by orsinium** [comment]
Documentation also implemented, but in #128

**Comment by dbanty** [comment]
Oops, sorry about that I didn’t see the duplicate issue. Always ahead of me.

**Comment by orsinium** [comment]
Don't worry, feel free to open any issues :)
