### ISSUE TITLE
Configurable project bump VCS Behavior

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#131]
Related to #130, I think it would be useful to configure the behavior of the commit/tag functionality of project bump.  Examples of useful options would be:

1. Custom commit message template
2. Custom tag format (e.g. 1.2.0 instead of v.1.2.0)
3. Ability to disable the commit/tag function altogether (if intending to do it manually as part of a larger release process)

**Comment by orsinium** [comment]
Closed in #114, will be in next release :) You can use dev-version for a while.
