### ISSUE TITLE
Contributors Guide

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#139]
Was wondering if we could have something like a `CONTRIBUTING.md` file with some basics on getting started.  As evidenced by #127 it's not too clear on how to start writing code without breaking things.  As a rule, the first thing I like to do when working on a project is make sure I can run the current tests so I have a baseline to know I didn't break anything when I make changes.

Here's a series of questions that I have so far that I'd hope to make it into some sort of guide for future contributors.  Maybe as I keep asking questions I can just start putting the answers into one common location 😄.

1. How do I run the tests?  Again, per #127, `dephell project test` doesn't seem to be the way to go.  I also tried doing a `dephell venv create` and `dephell deps install` then `dephell venv shell` and `pytest` but that told me more_itertools was not installed.  `dephell venv run --env pytest` didn't get me much futher.
2. What's the style guide?  As far as I can gather, it's basically follow PEP8 and use single quote strings.  Can I use a tool like [black](https://github.com/python/black) if I turn off the double quote string check?
3. How to use dephell with an IDE?  Maybe this is more of a general question, but I use PyCharm which needs to know which virtual environment it should be pointing to.  With Poetry or Pipenv I just configure it to put the virtual environment in the project (.venv) so it's easy to find.  Is there a similar option for dephell?
4. Is there a test coverage requirement for committing new code?

**Comment by dbanty** [comment]
Answering some of my own questions:
1. The answer seems to be to create venv, install deps, then run all with --env=pytest.  This is the same way travis does it, so we should put that process in this contributors file.
2. Flake8 is the tool to use.  Black seems to disagree on when to use trailing commas, so it's not usable with the flake8 tool.  I'll have to find some other auto-formatter to use with my IDE so I don't have to constantly check flake8 and fix issues one at a time.
3. For now I just did `dephell venv shell` then `which python`, then copied the path into PyCharm.  There's probably a better way.

**Comment by orsinium** [comment]
You can specify path to venv in cli or config:
dephell venv create --venv=.venv

I will have a look on all your questions and PRs later, now I'm moving into another apartment, it takes my free time :)

**Comment by orsinium** [comment]
Black isn't strict enough for big projects like DepHell, sorry:
https://articles.life4web.ru/eng/python-black/

**Comment by dbanty** [comment]
Good luck on your move!

That article is a bit out of date, they’ve fixed most of the problems with Black now. Poetry actually uses Black which is how I heard of it. I’m not trying to convince you because I think Black is better, just easier :P. I’ll take a look at YAPF and see if I can get it to do some of the work.

**Comment by orsinium** [comment]
No, article is actual, all output made by latest black in this week.

That's up to you what you're using on your environment. However, I think, you'll spend less time on following current styleguide than on adopting autoformatter for it.

**Comment by orsinium** [comment]
Fixed in #146
