### ISSUE TITLE
How to bump version from pre-release to release?

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#142]
Say I'm using semver and I have a candidate 0.2.0-rc.4 which has passed whatever testing process it needed to, and I wanted to release 0.2.0, how do I do that?

**Comment by orsinium** [comment]
Oh, I didn't catch this case. It have to be implemented, sorry

**Comment by dbanty** [comment]
Not a problem. I’m happy to take a crack at it if you want. Do you have an idea of how you’d want to do this? Realistically if you’re using a prerelease system you want to go to the prerelease before the real one (e.g. go straight from 0.2.0 to 0.3.0-rc.0 without needing to go to 0.3.0 first). 

Poetry does this with premajor, preminor, and prepatch rules. Then you can use the normal rule (e.g. minor) to go to the full, non-pre version. Could do something similar here.

**Comment by orsinium** [comment]
Sounds good. Additionally, maybe, rule `release` will be also good to just drop prerelease and dev parts from version. What do you think?

**Comment by orsinium** [comment]
Also, I thought about moving version management core into separated package, like `dephell_pythons`, to allow reusage of this logic in other projects without depending on dephell. And make rules pluggable. What do you think, is it sound reasonable, or "gram, stop making packages"? :)

**Comment by dbanty** [comment]
I agree with the `release` rule for sure.  

I also agree with splitting version management, I'm all about modular and reusable code.  I'm firmly in the "Gram, keep making packages!" camp.  Should definitely be a separate issue for that task though.

**Comment by dbanty** [comment]
@orsinium some questions:
1. Should we support all the pre-rules wherever both pre and the rule are supported?  Meaning if a scheme supports `VERSION_PRE` and `VERSION_MAJOR` should it get `VERSION_PRE_MAJOR` and `VERSION_RELEASE`?
2. Should I add these new rules as rules?  Or should the pre[rule] be a special case and we just look for the "pre" prefix and apply both "pre" and whatever rule (if any) is specified?
3. If going with explicit rules (e.g. `VERSION_MAJOR`) and if the answer to 1 is yes, would you rather auto-add rules to the schemes if they should support them (using some sort of loop) or explicitly add the rules by hand?

I think I know what your answers will be, and I'm going to proceed with these assumptions, I just want your opinion in writing (shamelessly gathering info for #139).  I think the answers will be:
1. Yes
2. Don't do fancy split string logic stuff, just do new rules.  More explicit, less hard to understand.
3. Write them in by hand for the same reason as 2.

Two more questions- these are just learning about your style, I'm not planning on refactoring anything.

4. Why tuples instead of sets for the rules?  Seems the primary use is with an `in` operator.
5. Why a big functional style processing of rules for all schemes (`bump_version()`) instead of scheme classes that know how to process rules?

**Comment by orsinium** [comment]
It's up to you. Explicit rules are better because these constants used in validations in config, for example, and will be used in rules listing command (#143).

Tuples used to order rules in output of validators, cli help and #143 command.

I totally agree. Big function is used because `dephell actions` contains only simple functions, this is the goal of this module. However, this function isn't simple anymore. So, as I mentioned in #143, I'm going to move it into separated module and make rules pluggable. "Pluggable" means classes :)

**Comment by orsinium** [comment]
Fixed in #144
