### ISSUE TITLE
Add a method for listing available rules for versioning scheme

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#143]
Not sure if `dephell project bump --help` is the right place for this (in which case this could be done in #121) or if a dedicated option like `dephell project bump --rules` is better.  The idea would be that dephell checks which versioning scheme you're using and lists the rules that are available to you.

**Comment by orsinium** [comment]
We need ideas about the name for it. `dephell project bumpers`? :)

**Comment by dbanty** [comment]
Should this be a separate command or just an option somewhere in the `bump` command.  Will listing the rules be useful outside the context of `bump`?

**Comment by orsinium** [comment]
I think, good place for it `dephell inspect versioning` with showing current version, versioning scheme, and available rules. It's most readable name I can imagine.

**Comment by dbanty** [comment]
Should probably wait until after #147 is done to do this, since much of the code will be moving around.
