### ISSUE TITLE
dephell master branch could not be install via `poetry install`

### ISSUE THREAD

**Issue by CircleOnCircles** [dephell/dephell#152]
While I was trying to diagnose #151 issue.

Steps:
1. I forked and git clone the `master` branch
2. try to install dependency via `poetry install` before start working
3. Found an error, probably due to corrupt `pyproject.toml`

### Error Message
```bash
$ poetry install    
.                           
[KeyError]  
'version'                
                           
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

I failed to install the dependency required to work with the dephell.
Are there any obvious things I missed?

**Comment by orsinium** [comment]
Could you provide traceback, please? 

```
poetry install -vvv
```

**Comment by CircleOnCircles** [comment]
$ poetry install -vvv
                           
[KeyError]  
'version'                
                           
Exception trace:
 /home/cocs/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/cocs/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/cocs/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/cocs/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/cocs/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /home/cocs/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 18
   current_env = Env.get(self.poetry.file.parent)
 /home/cocs/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /home/cocs/.poetry/lib/poetry/console/application.py in poetry() at line 60
   self._poetry = Poetry.create(os.getcwd())
 /home/cocs/.poetry/lib/poetry/poetry.py in create() at line 148
   package.add_dependency(name, constraint)
 /home/cocs/.poetry/lib/poetry/packages/package.py in add_dependency() at line 292
   version = constraint["version"]

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]

**Comment by dbanty** [comment]
Issue is with lines 128-133 on pyproject.toml FYI.  You can comment these out for now to make Poetry work.  I think we just need to specify version

```
# optional
aiofiles = {optional = true}
autopep8 = {optional = true}
colorama = {optional = true}
graphviz = {optional = true}
yapf = {optional = true}
```

**Comment by orsinium** [comment]
Yes, I think it too. We have to drop these lines from poetry converter:

```
# do not specify version explicit

if result['version'] == '*':

del result['version']
```

I messed up poetry and pipenv behavior :)

**Comment by orsinium** [comment]
@CircleOnCircles, do you want to make PR for it? :)

**Comment by CircleOnCircles** [comment]
> @CircleOnCircles, do you want to make PR for it? :)

yep!
