### ISSUE TITLE
Change "ERROR env {name} not found" to something more informative

### ISSUE THREAD

**Issue by MrMrRobat** [dephell/dephell#196]
When I execute `$ dephell venv create --env=tests`, i get this error:
```ERROR env `tests` not found```
Which could be quite confusing as I'm basicaly trying to create it.

It turns out, that error pointing to missing config for env, but not for the env itself.

So how about to change this error to something more suitable and informative, like:
```ERROR: env `tests` not found in config``` or 
```ERROR: section `[tool.dephell.tests]` not found in config```

**Comment by orsinium** [comment]
You're right! Do you want to make PR for it?

**Comment by Luttik** [comment]
This error still is not really informative. What should be expected in [tool.dephell.tests]?
If I read the [docs](https://dephell.readthedocs.io/cmd-deps-convert.html#filter-dependencies) U find that using envs is a method to filter which dependencies to install. 

Having to tag them and not just having `--envs main` and `--env dev` work is very weird, but having to configure it more is even weirder 

I can't find anywhere in the docs: 
- why we need to do so
- what it expects as conifguration 
- that it even needs to be done.
