### ISSUE TITLE
Add isort

### ISSUE THREAD

**Issue by b0g3r** [dephell/dephell#201]
isort has awesome settings and allows separate modules by customs blocks (also flake8 has integration plugin with isort)

For example our isort config for one of the projects:
```
[isort]
multi_line_output = 3
force_grid_wrap = 2
include_trailing_comma = true
default_section = FIRSTPARTY
line_length = 100
known_first_party = <special_core_external_lib>,
known_django=django,drf_yasg,rest_framework
sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```

**Comment by b0g3r** [comment]
Why? Because I find `# project/built-in/external` is non-controlled for multiple maintainers

**Comment by b0g3r** [comment]
Good candidate for the project, I think
```
[isort]
multi_line_output = 3
include_trailing_comma = true
default_section = FIRSTPARTY
line_length = 120
known_dephell = dephell-archive,dephell-discover,dephell-licenses,dephell-links,dephell-markers,dephell-pythons,dephell-shells,dephell-specifier,dephell-venvs,dephell-versioning
sections=STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,DEPHELL,LOCALFOLDER
```

Or merge dephell sections with firstparty

**Comment by orsinium** [comment]
Dephell already uses isort. See pyproject.toml. These comments inserted automatically by isort too. I'm just not forcing isort usage and sorting project imports time-to-time. Next sorting planned after vendorization merging :) I'll close the issue in that pr to let you know.
