### ISSUE TITLE
ModuleNotFoundError: No module named 'bowler'

### ISSUE THREAD

**Issue by b0g3r** [dephell/dephell#216]
I use poetry as a dependency manager for my project:
```
 ✘  ~/PycharmProjects/template-test   dev ●  poetry --version
Poetry 0.12.17
```

Also I use dephell as version bumper. In `pyproject.toml`:
```
[tool.poetry.dev-dependencies]
dephell = "==0.*,>=0.7.5"
```

```
 ~/PycharmProjects/template-test   dev ●  poetry show bowler
name        : bowler
version     : 0.0.1 
description : a hat 
```

But I receive an error if call any of dephell commands

```
 ~/PycharmProjects/template-test   dev ●  poetry run dephell
Traceback (most recent call last):
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/bin/dephell", line 6, in <module>
    from dephell.cli import entrypoint
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/cli.py", line 9, in <module>
    from .commands import COMMANDS
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/commands/__init__.py", line 2, in <module>
    from .auth import AuthCommand
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/commands/auth.py", line 9, in <module>
    from .base import BaseCommand
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/commands/base.py", line 12, in <module>
    from ..actions import attach_deps, get_python_env
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/actions/__init__.py", line 16, in <module>
    from ._transform import transform_imports
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/template-test-py3.7/lib/python3.7/site-packages/dephell/actions/_transform.py", line 1, in <module>
    from bowler import LN, Capture, Filename, Query
ModuleNotFoundError: No module named 'bowler'
```

Also, I have an error when tried to import bowler manually:
```
 ~/PycharmProjects/template-test   dev ●  poetry run python
Python 3.7.3 (default, Jul 10 2019, 22:48:45) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bowler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bowler'
```

**Comment by b0g3r** [comment]
Looks like poetry installs the 0.0.1 version of bowler package 🤔

**Comment by b0g3r** [comment]
✘  ~/PycharmProjects/template-test   dev ●✚  poetry debug:resolve bowler               
Resolving dependencies... (0.5s)

Resolution results:

  - bowler (0.0.1)
 ~/PycharmProjects/template-test   dev ●✚  poetry debug:resolve 'bowler >=0.7'
Resolving dependencies... (0.0s)
                                                                                                                    
[SolverProblemError]                                                                                 
Because no versions of bowler match >0.7,<0.7.1 || >0.7.1,<0.8.0 || >0.8.0                                        
 and bowler (0.7.0) depends on fissix (*), bowler (>=0.7,<0.7.1 || >0.7.1,<0.8.0 || >0.8.0) requires fissix (*).  
And because bowler (0.7.1) depends on fissix (*)                                                                  
 and bowler (0.8.0) depends on fissix (*), bowler (>=0.7) requires fissix (*).                                    
So, because no versions of fissix match *                                                                         
 and template-test depends on bowler (>=0.7), version solving failed.                                             
                                                                                                                    
debug:resolve [-E|--extras EXTRAS] [--python PYTHON] [--tree] [--install] [--] [<package>]...

**Comment by b0g3r** [comment]
If I add `fissix` as additional requirements it works:
```
[tool.poetry.dev-dependencies]
dephell = "==0.*,>=0.7.4"
fissix = "==19.2b1"
```

``` 
~/PycharmProjects/template-test   dev ●✚  poetry run dephell project bump minor
INFO generated new version (old=0.7.0, new=0.8.0)
INFO file bumped (path=/Users/Boger/PycharmProjects/template-test/template_test/__init__.py)
```

**Comment by orsinium** [comment]
What if you drop dephell and fissix and add `bowler = "*"`? Can poetry resolve it?

**Comment by b0g3r** [comment]
Nope. See `poetry debug:resolve`

чт, 11 июля 2019 г., 9:43 Gram <notifications@github.com>:

**Comment by orsinium** [comment]
So, it's a bug in poetry's resolver. I can do nothing about it. Please, open an issue in poetry's repository.

**Comment by b0g3r** [comment]
I think It's because '*' not about beta-requirements, isn't it?

**Comment by orsinium** [comment]
Meh. Right, let's make version more specific

**Comment by b0g3r** [comment]
When a new release?

**Comment by orsinium** [comment]
After #215 and #49, I think. Having features in every release is really important for a young project. I hope, it means "Sunday"

**Comment by adamcharnock** [comment]
@orsinium, I believe I've encountered an error related to the above fix. I just attempted to install dephell 0.7.6 as follows:

```toml
[tool.poetry.dev-dependencies]
dephell = ">=0.7.6"
fissix = "==19.2b1"
```
But received the error:

```
$ poetry update
Updating dependencies
Resolving dependencies... (0.3s)

[SolverProblemError]
Because dephell (0.7.6) depends on fissix (*)
 and no versions of dephell match >0.7.6,<0.7.7 || >0.7.7, dephell (>=0.7.6,<0.7.7 || >0.7.7) requires fissix (*).
And because dephell (0.7.7) depends on fissix (*), dephell (>=0.7.6) requires fissix (*).
So, because no versions of fissix match *
 and mate3 depends on dephell (>=0.7.6), version solving failed.
```

Adding `fissix` as follows fixed the problem:

```toml
[tool.poetry.dev-dependencies]
dephell = ">=0.7.6"
fissix = "==19.2b1"
```

**Comment by orsinium** [comment]
Yeah, right, we haven't released it yet. Soon.
