### ISSUE TITLE
Preserve NPM-style constraints for Poetry

### ISSUE THREAD

**Issue by b0g3r** [dephell/dephell#229]
In our pyproject.toml we have poetry formatted requirements like these:

`sentry_sdk = "^0.9.0"`

and

`reponame = { git = "ssh://git@our-git-server:port/group/reponame.git", branch = "v3_2" }`

But dephell rewrites it to

```
sentry-sdk = "==0.*,>=0.9.0"
cindicator-backend = {git = "git@git@our-git-server:port:group/reponame.git", rev = "v3_2", version = "*"}
```

It rudely breaks our workflow

**Comment by orsinium** [comment]
Yes, DepHell transforms npm-style constraints into PEP-440 compatible. We can make `.to_npm()` method in [dephell_specifier](https://github.com/dephell/dephell_specifier) to make backward conversion if possible. Or store original constraint in the `Specifier`. Don't you mind if I'll move it into `dephell_specifier` repo?

**Comment by b0g3r** [comment]
I think that changing "my-style" pyproject.toml is a bad idea, if I just try to bump version.

Also, after bumping we lost `ssh` and get broken `group` path in git requirements.

**Comment by orsinium** [comment]
Make a new issues for these diffs, please, to make it possible to track it.
