### ISSUE TITLE
cached-property dependency

### ISSUE THREAD

**Issue by asouini** [dephell/dephell#24]
it seems that https://pypi.org/project/cached-property/ is missing in en dependency list, i have to install it manually

`python3 -m pip install dephell[all] cached-property`

**Comment by orsinium** [comment]
Yeah, thank you. It is fixed in `test-command` branch. I will release it soon :)

**Comment by orsinium** [comment]
BTW, release on pypi really old, version on git much cooler yet.

**Comment by asouinisfc** [comment]
> BTW, release on pypi really old, version on git much cooler yet.

cool tool you have here no doubt, i came from your poetry-setup project to this one and there is sure big improvements

**Comment by asouini** [comment]
> BTW, release on pypi really old, version on git much cooler yet.

cool tool you have here no doubt, i came from your poetry-setup project to this one and there is sure big improvements

**Comment by orsinium** [comment]
Uploaded! Please, update Dephell to the version 0.4.0:

```bash
pip install -U --no-cache-dir dephell
```

This is the first release on pypi that fully tested and built by dephell itself :)
