### ISSUE TITLE
'python_requires' invalid version specifiers

### ISSUE THREAD

**Issue by asouinisfc** [dephell/dephell#25]
hi,

i encountered this issue while using another tool on the setup.py file generated  using dephell (stdeb with debianize command)

> 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=2.7.0 || ==3.*'

i checked and that specifier doesn't seem correct (no OR in the specification of versions)

**Comment by orsinium** [comment]
Yeah, thank you. DepHell has no conversion from OR format yet. It's supported only by dephell and poetry.I will implement it. BTW, you can write `>=2.7,<4.0` instead of `>=2.7.0 || ==3.*`

**Comment by asouini** [comment]
> Yeah, thank you. DepHell has no conversion from OR format yet. It's supported only by dephell and poetry.I will implement it. BTW, you can write `>=2.7,<4.0` instead of `>=2.7.0 || ==3.*`

yeah i did that, but i am using dephell in an automated pipeline to build a python project debian package, i modify the generated setup.py file using sed.

still this tool is promising, ill be checking it out in the close futur !

**Comment by orsinium** [comment]
Fixed. Please, update dephell to 0.5.1

**Comment by orsinium** [comment]
And feel free to open any new issues :)
