### ISSUE TITLE
setup.py package_data should be sorted for smaller diffs

### ISSUE THREAD

**Issue by kstrauser** [dephell/dephell#265]
Whenever I run `dephell deps convert --from=pyproject.toml --to=setup.py`, the ordering of the `package_data={...}` dict is unstable and changes between every run. The actual contents don't change, just their ordering.

We're in the long process of upgrading a particular project from setup.py to Poetry, and as part of our new build process we run `dephell deps convert` quite frequently. This makes for some very noisy diffs as the resulting `setup.py` is constantly changing, even though it's not really.

Would it be possible to sort the keys in `package_data` before writing them out so that the output only changes whenever something is legitimately different?

**Comment by orsinium** [comment]
Thank you for feedback. Which Python version do you use?

**Comment by kstrauser** [comment]
This is with Python 3.6.9.

**Comment by ko3luhbka** [comment]
Hi, I'd like to take this issue, is it okay?

**Comment by orsinium** [comment]
Sure, keep going!

**Comment by ko3luhbka** [comment]
I'm working on it, I think I'll finish on weekend.

**Comment by orsinium** [comment]
How is it going? You can try to use `json.dump(..., sort_keys=True)` here. I think for this part syntax of JSON and Python will be the same. Also, #292 does almost the same, but it's in WIP yet.

**Comment by ko3luhbka** [comment]
@orsinium yes, that's exactly what I used. There was also a kind of tricky thing for me with outer quotes of the string produced by `json.dump` but it's gone if `!r` is changed to `!s` in string formatting. 
Now I just want to write a couple of tests but I stuck a bit with existing tests - some of them fail even without my changes applied. I'll try to investigate it tomorrow, probably some environment problems.

**Comment by orsinium** [comment]
Fixed in #292
