### ISSUE TITLE
Exclude .pyc files from sdist

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#283]
When doing distro packaging, comparisons of the old and new sdist tarballs is a safety measure to ensure nothing suspect has slipped in.  The .pyc files in the sdists create a lot of noise in that process.

**Comment by jayvdb** [comment]
See e.g. https://build.opensuse.org/package/rdiff/home:jayvdb:py-dephell-roundtrip/python-dephell?opackage=python-dephell&oproject=devel%3Alanguages%3Apython&rev=6

**Comment by orsinium** [comment]
Thank you for your report! Duplicate of #103. I also really want to see it fixed :)
