### ISSUE TITLE
setup.py round-trip experiment

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#284]
I have set up an OBS project which builds 71 core Python packages, but it also first runs 

```sh
python3 -m dephell deps convert --traceback --from=setup.py --to=pyproject.toml
python3 -m dephell deps convert --from=pyproject.toml --to=setup.py
```

Roughly 50% pass.  40 builds pass.  48 builds fail. (88 != 71 because many of these packages have a separate build for the tests to avoid cyclic dependencies)  The 40 that build doesnt mean they are all correct, but it is a good sign, as it usually means a test suite was run and they passed.

First thing was a lot of builds failed with `LookupError: cannot determine converter for file: pyproject.toml`

That occurs if the project already has a `pyproject.toml`, e.g. https://github.com/python-attrs/attrs and https://github.com/pyca/bcrypt/ . Adding `--to-format=pyproject` doesnt help.  Deleting the `pyproject.toml` before hand does work.  A force option might be nice, or a better error message.  In the case of both `attrs` & `bcrypt`, its pyproject uses `build-backend = "setuptools.build_meta"` , converting from it to `setup.py` also fails. `zipp`, `pip`, `python-dateutil`, `cryptography`, `virtualenv`, `importlib_resources` and `importlib-metadata` all look similar.

I also hack around projects which use `src` sub-directories - c.f. https://github.com/dephell/dephell/issues/257 .  Some projects fail because of my hack, such as `future`, probably `hypothesis`.

https://build.opensuse.org/project/show/home:jayvdb:py-dephell-roundtrip

The added build logic can be seen at
https://build.opensuse.org/projects/home:jayvdb:py-dephell-roundtrip/prjconf

The outcomes
- setup.py `if __name__ == '__main__':` ignored, e.g. https://github.com/box/flaky https://github.com/kjd/idna/ , also `wcwidth`, `setuptools` and `setuptools_scm` possibly failing for this reason.
- `py_modules` appears to be ignored e.g. `six` https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-six repo https://github.com/benjaminp/six/ , also `appdirs` and `pyparsing` and many others, and *nothing* is installed because they have no package directories.
- setup.py `packages` ignored - extra packages found and added.  e.g. `dev` package added for https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-asn1crypto , so when `python2 setup.py test` runs, unexpectedly extra tests are run, and they fail due to missing deps.  `colorama` also fails for this reason.
- pbr setup.cfg  `[files] packages = ..` is ignored and `test` package is included. The output includes `ERROR distribution was not called` e.g. https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-py2pack repo https://github.com/openSUSE/py2pack/
- string entry_points causes `AttributeError: 'str' object has no attribute 'items'` c.f. https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-Babel http://babel.pocoo.org/ and `setuptools-git`
- The setup.py parser should fail when it has zero chance of generating correct output, e.g. https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-cffi repo https://bitbucket.org/cffi/  
- `ModuleNotFoundError: No module named 'x'` occurs when `x` is the package being installed, or another module found in the local directory, which needs to be added to `sys.path`.  e.g. [Cython](https://build.opensuse.org/package/show/home:jayvdb:py-dephell-roundtrip/python-Cython) and `pbr`, `nose`, `lxml` and `metaextract`, `termcolor`.
- `mock` - `AttributeError: 'NoneType' object has no attribute 'group'`  then `InvalidSpecifier: Invalid specifier: 'UNKNOWN'` - this looks like it might be caused by mock's setup.py trying to read from a file inside of `mock/`, but that is only a wild guess.
- `pyasn1` - `test` command isnt implemented, and this package has two failures until unittest which dont occur when its cmdclass using pytest is activated.  Given the status of `python setup.py test`, I dont expect this one to be a high priority ;-)  Likely `tzlocal` also failing for this reason.
- `unittest2`: `/usr/lib/python3.7/site-packages/setuptools/dist.py:484: UserWarning: The version specified (<__main__.late_version object at 0xb6e4372c>) is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.` during convert and then `AttributeError: 'late_version' object has no attribute 'strip'` during `build`.  The version value is a class which implements `__str__()` to return the string; effectively this is a delayed import trick, and setuptools doesnt like it now, but I am quite sure that warning didnt exist in 2015.

**Comment by jayvdb** [comment]
unittest2 warning raised as https://github.com/pypa/setuptools/issues/1889

**Comment by orsinium** [comment]
Thank you for cool research. We've switched on [dephell_setuptools](https://github.com/dephell/dephell_setuptools), and I hope most of the cases are fixed.

> LookupError: cannot determine converter for file: pyproject.toml

That's because it can be "flit" or "poetry", and dephell tries to determine the right format from the file content (find `tool.poetry` or `tool.flit`). When there is no file at all, dephell assumes the most popular format (it's poetry, unfortunately).

>  Adding --to-format=pyproject doesnt help

That's incorrect format. This one works with `build-system.requires` content. I don't know why I even added it :D You need `--to-format=poetry` or `--to-format=flit`.
