### ISSUE TITLE
convert setuppy output filename ignored

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#288]
`python3 -m dephell deps convert --traceback --from setup.py --to setup.py.new --to-format setuppy` should create a file `setup.py.new` which is a parse and dump of the existing `setup.py`

Instead it writes to `setup.py` (and for dephell repo it changes stuff :P)

**Comment by orsinium** [comment]
You specified `--to` instead of `--to-path` :) I've created #307 to be explicit about it.
