### ISSUE TITLE
setup.py generation isnt stable

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#289]
In dephell repo `python3 -m dephell deps convert --traceback --from setup.py --to setup.py` results in the following diff on Pythoon 3.7

```diff
diff --git a/setup.py b/setup.py
index 9c3f005..4c1c1f3 100644
--- a/setup.py
+++ b/setup.py
@@ -24,11 +24,6 @@ setup(
     version='0.7.8',
     description='Dependency resolution for Python',
     python_requires='>=3.5',
-    project_urls={
-        'homepage': 'https://dephell.org/',
-        'repository': 'https://github.com/dephell/dephell',
-        'documentation': 'https://dephell.org/docs/'
-    },
     author='Gram',
     author_email='master_fess@mail.ru',
     license='MIT',
@@ -66,13 +61,9 @@ setup(
     extras_require={
         'full': ['aiofiles', 'autopep8', 'colorama', 'graphviz', 'yapf'],
         'tests': ['aioresponses', 'pytest', 'requests-mock'],
-        'dev': [
-            'aioresponses', 'alabaster', 'flake8-isort', 'isort[pyproject]',
-            'pygments-github-lexers', 'pytest', 'recommonmark', 'requests-mock',
-            'sphinx'
-        ],
         'docs': [
-            'alabaster', 'pygments-github-lexers', 'recommonmark', 'sphinx'
+            'alabaster', 'flake8-isort', 'isort[pyproject]',
+            'pygments-github-lexers', 'recommonmark', 'sphinx'
         ]
     },
 )
```

The order of the extras appears to be unsorted.
(project_urls is dropped but that may be due to the metadata not being available from parse phase)

**Comment by jayvdb** [comment]
There is something strange happening with extra `dev`, which I do not quite understand.

https://github.com/dephell/dephell/blob/d9b3c96/dephell/converters/setuppy.py#L148
`envs = {extra} if extra == 'dev' else {'main', extra}`

**Comment by orsinium** [comment]
> `envs = {extra} if extra == 'dev' else {'main', extra}`

Any dependency belongs either to `dev` or `main`, but not at the same time. Also, it can have additional envs: this is "extra" in pip-terms. So, what's going on here:

1. If extra named dev, we're saving it as `dev`. 
2. If it's something like `tests`, we're assuming it's in `main`.

In other word, from setup.py dependency can be in `dev` only if `extra` named `dev`. When DepHell dumps dep with extra `{'dev', 'tests'}`, it puts deps in both extras.

Things are different a little bit with poetry. In poetry you can put dependency in either `dependencies` or `dev-dependencies` section, and then in `extras` point on dependency from any section.

**Comment by orsinium** [comment]
Another thing to discuss about idempotency: we have prettying of file with yapf, black, autopep8. Maybe, something else. But the thing is all these dependencies are optional. So, output also depends on optional dependencies. However, I don't think it's a good idea to depend on anything from this list. At least while we need it only for setup.py. What do you think?

**Comment by jayvdb** [comment]
I agree it isnt a good idea to depend on python prettifiers if only needed for `setup.py`. https://github.com/dephell/dephell/pull/293 also adds `metaextract`.  Maybe it is good to have an extra `setuppy`, or even have a plugin system for these file formats.

**Comment by orsinium** [comment]
We're using setup.py in resolving for reading sdists from pypi. So, we can't make it optional.
