### ISSUE TITLE
Documentation improvement: Add dates to change log entries

### ISSUE THREAD

**Issue by jonathanchukinas** [dephell/dephell#314]
I'm excited for this project. The first thing I did when looking at the docs was to see when it started and when the last release was. But there aren't any dates in the change log.  I had to go to PyPI to find the info.

Thanks!

**Comment by orsinium** [comment]
Use `dephell package releases dephell`, dephell helps with things like this ;)

Anyway, let's add this. :+1:

**Comment by orsinium** [comment]
Oh, and we have releases on Github, it stores dates

**Comment by jonathanchukinas** [comment]
Oh I know I can find the info elsewhere. It's mostly an issue of marketing. Someone (like me) stumbles over your documentation and immediately wonders how active the project is.

**Comment by jonathanchukinas** [comment]
Two projects I'm a big fan of date their change logs:
- https://click.palletsprojects.com/en/7.x/changelog/
- https://openpyxl.readthedocs.io/en/stable/changes.html
