### ISSUE TITLE
Wrong dependency ... dephell-setuptools>=0.2.1 cannot be resolved

### ISSUE THREAD

**Issue by mcepl** [dephell/dephell#316]
### Required Information

Please attach the output of the following commands

* [x] Output of failing Dephell command with `--traceback` and `--level=DEBUG` flags set
* [x] Project's current Dephell config
* [x] Output of `dephell inspect self`

[   42s] + dephell deps convert --from pyproject.toml --to setup.py
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
[   42s]     ws.require(__requires__)
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
[   42s]     needed = self.resolve(parse_requirements(requirements))
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
[   42s]     raise VersionConflict(dist, req).with_context(dependent_req)
[   42s] pkg_resources.ContextualVersionConflict: (dephell-setuptools 0.1.2 (/usr/lib/python3.7/site-packages), Requirement.parse('dephell-setuptools>=0.2.1'), {'dephell'})
[   42s] 
[   42s] During handling of the above exception, another exception occurred:
[   42s] 
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/bin/dephell", line 6, in <module>
[   42s]     from pkg_resources import load_entry_point
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
[   42s]     @_call_aside
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
[   42s]     f(*args, **kwargs)
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
[   42s]     working_set = WorkingSet._build_master()
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
[   42s]     return cls._build_from_requirements(__requires__)
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
[   42s]     dists = ws.resolve(reqs, Environment())
[   42s]   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
[   42s]     raise DistributionNotFound(req, requirers)
[   42s] pkg_resources.DistributionNotFound: The 'dephell-setuptools>=0.2.1' distribution was not found and is required by dephell
[   42s] error: Bad exit status from /var/tmp/rpm-tmp.PiZl7k (%prep)

For more information, see the `CONTRIBUTING` guide.

### Description

setup.py has incorrect dependencies. It is hard for dephell to depend on dephell_setuptools >= 0.2.1, when the last released version is 0.1.2 (it is an obvious typo).

### Steps to Reproduce

1. Run any debhell command

**Expected behavior:** [What you expected to happen]
Something, anything.

**Actual behavior:** [What actually happened]
Crash as shown above.

[Complete build log](https://github.com/dephell/dephell/files/3908700/_log.txt)

[Proposed patch](https://github.com/dephell/dephell/files/3908704/fix_dephell_setuptools_deps.patch.txt)

**Comment by mcepl** [comment]
This is completely wrong. Sorry.

**Comment by orsinium** [comment]
> This is completely wrong. Sorry.

So, what's happened?

**Comment by mcepl** [comment]
There is no more recent release on https://github.com/dephell/dephell_setuptools/releases than 0.1.2, not sure where the releases on https://pypi.org/project/dephell-setuptools/ are from.

**Comment by orsinium** [comment]
Thank you, I'll take care of it. It's my fault. I see https://github.com/dephell/dephell_setuptools/issues/5 about it.
