### ISSUE TITLE
Links on search page are broken

### ISSUE THREAD

**Issue by rvanlaar** [dephell/dephell#325]
### Description

The search page in the documentation leads to broken links.

### Steps to Reproduce

1. search: https://dephell.org/docs/search.html?q=audit&check_keywords=yes&area=default
2. click on result: https://dephell.org/cmd-deps-audit.html

**Expected behavior:** [What you expected to happen]
To open the actual result

**Actual behavior:** [What actually happened]
The URL leads to a 404. The URLS that search returns are missing 'doc' in the path.

Thank you for reporting this issue! Every issue reported helps improve Dephell!

**Comment by rvanlaar** [comment]
It seems this can't be fixed in this repository but needs to be fixed by the maintainer.

After digging into how the documentation for dephell is build I found the following:
The docs are hosted by readthedocs and displayed through the server at dephell.org.

This server has a /doc/ path about which the search from readthedocs doesn't know about.

**Comment by orsinium** [comment]
That's true

https://github.com/dephell/dephell_homepage/blob/master/configs/nginx.conf#L43

I think it's better to do redirect instead of proxying. Readthedocs feels bad about my scheme :)

**Comment by orsinium** [comment]
Done :+1:

**Comment by rvanlaar** [comment]
It doesn't work yet.

I believe that is because the project domain is specified as dephell.org.

**Comment by orsinium** [comment]
Ah, right. Thank you. Now it works.
