### ISSUE TITLE
`jail show` command

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#33]
Command to show all useful information about jail. Like `inspect venv`, but with exposed entrypoints list.

**Comment by dbanty** [comment]
Is this different than `jail list`?

**Comment by orsinium** [comment]
Good question, thank you. Issue description isn't clear enough. `jail show` should show information about specific jail:

```bash
$ dephell jail show flake8
{
  name: "flake8",
  path: "...",
  size: "...",
  entrypoints: ["flake8"]
}
``` 

It's like `dephell inspect venv`, but shows information about venv of specific jail, not the current project.
