### ISSUE TITLE
dep convert can not handle flit-core / intreehooks

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#332]
https://github.com/takluyver/intreehooks is a new backend, used most prominently for flit-core https://github.com/takluyver/flit/blob/master/flit_core/pyproject.toml

dephell doesnt support it yet.

**Comment by orsinium** [comment]
Sorry, I didn't catch that. What exactly should be supported? Interhooks is about running a tool on installation. Dephell is about reading dependency files. Also, dephell can read `build-system.requires` with `pyproject` converter.

**Comment by jayvdb** [comment]
AH , looks like it is only the auto-detection of format which isnt working
```
> dephell deps convert --from pyproject.toml --to setup.py
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
ERROR LookupError: cannot determine converter for file: pyproject.toml 
```

When I specify `--from-format pyproject` it works.

**Comment by orsinium** [comment]
Ah, thanks. I'll check autodetection :)
