### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#343]
Well, let's give it a try. Now we have @espdev that helps us to fix #272. I'll link all related PRs here.

Goal: pass all the tests on win, exclude some of them for it.
Not a goal yet: checking win support on CI. That's insanely difficult, to be said!

**Comment by d3sbar** [comment]
Please note that fcntl import dependency for dockerpty\io.py fails - since fcntl has no windows support. consider alternatives like docker-py instead of PTY based access for cross-platform compatibility.

**Comment by orsinium** [comment]
Fix for it already in master. Thank you :)

> consider alternatives like docker-py

It's not an alternative, unfortunately. We use both of them. `dockerpty` provides one missed feature from `docker-py` that powers [dephell docker shell](https://dephell.readthedocs.io/cmd-docker-shell.html).

Would you like to contribute to the task? Get master, run tests, see what fails, share, try to fix. Everything that we already have is merged (except https://github.com/dephell/dephell_pythons/pull/4/files), so no merge conflicts expected.

**Comment by orsinium** [comment]
Let's consider it done. I'll announce the experimental support of Win in the next release (which I'm going to make today). Everything else will go as a separate issue.
