### ISSUE TITLE
Installer fails on Windows

### ISSUE THREAD

**Issue by fralik** [dephell/dephell#354]
## Short description

Windows installation fails when used with official python for windows distribution.

## Output

Expected outcome - dephell installed.

## Steps to reproduce

1. Install Python from https://www.python.org/downloads/release/python-376/
2. Verify that python is installed correctly:
    ```dos
    >python --version
    Python 3.7.6
    ```
3. `curl -L dephell.org/install | python`

## Details

First, the installer [searches](https://github.com/dephell/dephell/blob/a05bfad7c51d428f53ea0c114de88aab93808b61/install.py#L66) for python3. There is no `python3` binary on Windows.

Then, if I change it so that python is found, there is another error:
```rem
copy binary dephell
DepHell binary not found
```
Looking at files in virtual environment folder, it seems that dephell was indeed installed, but [local_path](https://github.com/dephell/dephell/blob/a05bfad7c51d428f53ea0c114de88aab93808b61/install.py#L104) fails as binary on Windows is `dephell.exe` and not `dephell`.

**Comment by orsinium** [comment]
Window support will be in the next release. Please, follow #343 for updates.
