### ISSUE TITLE
Manage documentation version

### ISSUE THREAD

**Issue by jhermann** [dephell/dephell#373]
The docs version is hardcoded and currently out-of-sync.

```console
$ grep ^version.= pyproject.toml docs/conf.py 
pyproject.toml:version = "0.8.1"
docs/conf.py:version = '0.7'
```

## Solution

Either add config / code that supports changing the version in `conf.py` via `project bump` (i.e. make that more customizable in general), or else add code into `conf.py` that either imports the version from the package, calls `python setup.py --version`, or parses it out of `project.toml`.

The latter is of course way less work, but limited to the use-case at hand.

**Comment by orsinium** [comment]
Right, it's on the way into dephell project bump
