### ISSUE TITLE
convert pyproject.toml with --envs main keeps dev packages

### ISSUE THREAD

**Issue by gsemet** [dephell/dephell#384]
Hi

For a pyproject.toml with:
```toml
[tool.poetry.dependencies]
python = ">=3.4"
boltons = "*"
pbr = ">=4"
structlog = "*"
typing = {version = "^3.7.4", python = "<3.5"}

[tool.poetry.dev-dependencies]
autopep8 = "*"
bandit = "*"
flake8 = "*"
flake8-coding = "*"
flake8-comprehensions = "*"
isort = "*"
m2r = "*"
more-itertools = "*"
mypy = "*"
pathlib2 = "*"
pycodestyle = "*"
pydocstyle = "*"
pyflakes = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-html = "*"
pytest-mock = "*"
requests = "*"
rope = "*"
sphinx = "*"
sphinx-autodoc-typehints = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-apidoc = "*"
yapf = "*"
dephell = "^0.8.1"
html5lib = "^1.0.1"
```
I want to convert to `requirements.txt` without frozening versions, keeping only `main` packages and keeping the markers when applicable.

Expected output:
```bash
$ cat requirements.txt
-i http://mycompany.pypiserver/pypi/simple
boltons
pbr>=4
structlog
typing ; python_version < '3.5'.
```

But I can't get dephell to successfully convert this file:
```bash
$ dephell deps convert --envs main --from=pyproject.toml --to=requirements.txt --level DEBUG
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
DEBUG load dependencies... (format=poetry, path=pyproject.toml)
DEBUG unapply by envs (dep=autopep8, envs={'main'})
DEBUG unapply by envs (dep=bandit, envs={'main'})
DEBUG unapply by envs (dep=flake8, envs={'main'})
DEBUG unapply by envs (dep=flake8-coding, envs={'main'})
DEBUG unapply by envs (dep=flake8-comprehensions, envs={'main'})
DEBUG unapply by envs (dep=isort, envs={'main'})
DEBUG unapply by envs (dep=m2r, envs={'main'})
DEBUG unapply by envs (dep=more-itertools, envs={'main'})
DEBUG unapply by envs (dep=mypy, envs={'main'})
DEBUG unapply by envs (dep=pathlib2, envs={'main'})
DEBUG unapply by envs (dep=pycodestyle, envs={'main'})
DEBUG unapply by envs (dep=pydocstyle, envs={'main'})
DEBUG unapply by envs (dep=pyflakes, envs={'main'})
DEBUG unapply by envs (dep=pylint, envs={'main'})
DEBUG unapply by envs (dep=pytest, envs={'main'})
DEBUG unapply by envs (dep=pytest-cov, envs={'main'})
DEBUG unapply by envs (dep=pytest-html, envs={'main'})
DEBUG unapply by envs (dep=pytest-mock, envs={'main'})
DEBUG unapply by envs (dep=requests, envs={'main'})
DEBUG unapply by envs (dep=rope, envs={'main'})
DEBUG unapply by envs (dep=sphinx, envs={'main'})
DEBUG unapply by envs (dep=sphinx-autodoc-typehints, envs={'main'})
DEBUG unapply by envs (dep=sphinx-rtd-theme, envs={'main'})
DEBUG unapply by envs (dep=sphinxcontrib-apidoc, envs={'main'})
DEBUG unapply by envs (dep=yapf, envs={'main'})
DEBUG unapply by envs (dep=dephell, envs={'main'})
DEBUG unapply by envs (dep=html5lib, envs={'main'})
DEBUG dump dependencies... (format=pip, path=requirements.txt)
INFO converted
```

But the output requirements still has some dev packages:
```bash
$ cat requirements.txt
-i http://mycompany.pypiserver/pypi/simple
autopep8
bandit
boltons
dephell==0.*,>=0.8.1
flake8
flake8-coding
flake8-comprehensions
html5lib==1.*,>=1.0.1
isort
m2r
more-itertools
mypy
pathlib2
pbr>=4
pycodestyle
pydocstyle
pyflakes
pylint
pytest
pytest-cov
pytest-html
pytest-mock
requests
rope
sphinx
sphinx-autodoc-typehints
sphinx-rtd-theme
sphinxcontrib-apidoc
structlog
yapf
```

When I convert to setup.py I have almost the right content:
```bash
$ dephell deps convert --envs main --from=pyproject.toml --to=setup.py --level DEBUG
...
$ cat setup.py
...
    install_requires=['boltons', 'pbr>=4', 'structlog'],
    extras_require={
        "dev": [
            "autopep8", "bandit", "dephell==0.*,>=0.8.1", "flake8",
            "flake8-coding", "flake8-comprehensions", "html5lib==1.*,>=1.0.1",
            "isort", "m2r", "more-itertools", "mypy", "pathlib2", "pycodestyle",
            "pydocstyle", "pyflakes", "pylint", "pytest", "pytest-cov",
            "pytest-html", "pytest-mock", "requests", "rope", "sphinx",
            "sphinx-autodoc-typehints", "sphinx-rtd-theme",
            "sphinxcontrib-apidoc", "yapf"
        ]
    },
```

Linked to https://github.com/python-poetry/poetry/issues/2009

**Comment by Galiley** [comment]
I had the same issues with this simple pyproject.toml,
```
[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pylint = "^2.4.4"
```
If i try to convert the pyproject.toml to pip format on stdout with only main dependencies, the expected output should be
```
click==7.*,>=7.1.1

INFO converted 
```
But instead I get
```
click==7.*,>=7.1.1
pylint==2.*,>=2.4.4
pytest==5.*,>=5.4.1

INFO converted 
```
After a quick search, I've narrowed the issue on these lines
https://github.com/dephell/dephell/blob/533d60ff2107a3012b4b8fad4fa82a5324a22651/dephell/commands/deps_convert.py#L67#L77

**Comment by Galiley** [comment]
# Description
I have the same issue. I have even tried it on the [sampleproject](https://github.com/pypa/sampleproject) to see if the issue wasn't comming from my project. @orsinium Is it a normal behaviour?

# Versions
```json
{
  "cache": "70.83Mb",
  "path": "/home/galiley/.local/lib/python3.8/site-packages/dephell",
  "python": "/usr/bin/python",
  "version": "0.8.2",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```

**Comment by Luttik** [comment]
Im also having this issue. Even when tagging the individual dependencies with #main and #dev (as per the [docs](https://dephell.readthedocs.io/cmd-deps-convert.html#filter-dependencies).

Additionally getting the error that we need to configure main / dev in my toml file is extremely weird.

I can't find anywhere in the docs: 
- why we need to do so
- what it expects as conifguration 
- that it even needs to be done.

**Comment by Luttik** [comment]
@orsinium 
I found that there are no tests for `deps convert` (I mainly looked [here](https://github.com/dephell/dephell/blob/master/tests/test_commands/test_deps_convert.py)). Therefore this unexpected behavior can go unnoticed.

I tried to copy the first test to amend it for this purpose myself. But I got a weird `ValueError` (it tries to make the path relative while it is not a subpath of the current folder) when trying to set the output format such that it outputs `requirements.txt`. I would be willing to help with this issue but It seems that there are some underlying issues in the testing suite that might need to be fixed first.

I think this is quite an important issue since it touches arguably the most core functionality of this package.

**Comment by orsinium** [comment]
> I found that there are no tests for deps convert (I mainly looked here). Therefore this unexpected behavior can go unnoticed.

You've pointed onto the integration test for it. Resolver and parts are covered by unit-tests in `tests/test_resolver/`.

> But I got a weird ValueError

Are you going to fill an issue or investigate it? If you don't report or fix it, nobody will do.

> It seems that there are some underlying issues in the testing suite that might need to be fixed first.

Great! Would you like to contribute? Add any tests you want, make PR, and link it to #34. DepHell is OSS and is driven by the community. No need to wait until I'll fix everything.

> Additionally getting the error that we need to configure main / dev in my toml file is extremely weird.

Sorry, I don't understand what do you mean. Do you use `Pipfile`? Then it has `[packages]` and `[dev-packages]` sections that are mapped to `main` and `dev`. If you're about filtering, it can be done in CLI as well by `--envs` command.

**Comment by Luttik** [comment]
@orsinium 
# In regards to your questsions for testing & contribution
I was trying to contribute by fixing this issue. I was simply working in the test module so I can do TTD.

I do think the behavior I found in the testing module was strange. But I see for me to assert that it should be done in some other way, the only reason that I brought it up is that it prevented me from contributing.

# In regards to Pipfile (and error)
1. `--envs` was broken for Pipfile as well but your fix for pyproject.toml also fixed it for Pipfiles.
2. I will open another issue for the error part. Everything works now (for my usecase) but there was some unexpected behavior along the way.
