### ISSUE TITLE
Add 'requirementstxt' as a format

### ISSUE THREAD

**Issue by geckon** [dephell/dephell#386]
## Short description

It would be really nice to be able to specify requirements.txt-like format. Quite often people use different requirements.txt files like `requirements.txt`, `requirements-dev.txt`, `requirements-test.txt`, etc. While converting e.g. to `pyproject.toml` this would help.

## Output

```
$ dephell deps convert --from=requirements-test.txt --to=pyproject.toml 
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
ERROR LookupError: cannot determine converter for file: requirements-test.txt
$ dephell deps convert --from=requirements-test.txt --from-format=requirementstxt --to=pyproject.toml 
usage: dephell deps convert [OPTIONS]
dephell deps convert: error: argument --from-format: invalid choice: 'requirementstxt' (choose from 'conda', 'egginfo', 'flit', 'imports', 'installed', 'pip', 'pipfile', 'pipfilelock', 'piplock', 'poetry', 'poetrylock', 'pyproject', 'sdist', 'setuppy', 'wheel')
```

## Steps to reproduce

Try and convert from _requirements.txt-like_ file that is not named `requirements.txt`.

## Config

independent of config

# Versions

```
$ dephell inspect self
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
WARNING cannot find module, trying to install (package=pygments)
Collecting pygments
Installing collected packages: pygments
Successfully installed pygments-2.5.2
{
  "cache": "0b",
  "path": "/home/theger/ws/showmax/es-models/venv/lib64/python3.7/site-packages/dephell",
  "python": "/home/theger/ws/showmax/es-models/venv/bin/python3",
  "version": "0.8.1",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}

```

**Comment by geckon** [comment]
Actually this is already possible:
```
dephell deps convert --from-path=requirements-test.txt --from-format=pip --to=pyproject.toml
```

Sorry, my bad!

**Comment by orsinium** [comment]
How did you miss it? Do you have an idea how to make docs better? When such confusion happens, first of all, I blame our docs. However, in this case I'm not sure what we can improve.

**Comment by geckon** [comment]
Honestly, I'm not really sure. Now I can see it's in the docs explained pretty well. Sorry, that was probably just my blindness.

**Comment by orsinium** [comment]
#409 is merged and released. Now, `requirements-test.txt` also will be detected as `pip` format, without explicit specification. It should help :) The help message is attached to the issue description. It says that it's unknown `--from-format` and shows al possible values.

**Comment by orsinium** [comment]
Please, upgrade dephell to 0.8.2.

**Comment by geckon** [comment]
Thanks for caring!
