### ISSUE TITLE
[Meta] dephell.org is down?

### ISSUE THREAD

**Issue by dataframing** [dephell/dephell#422]
## Short description

I think `dephell.org` is down. I can't seem to run the installation command due to a cURL error. Likewise, visiting `dephell.org` gives me an error. Visiting [https://downforeveryoneorjustme.com/dephell.org](https://downforeveryoneorjustme.com/dephell.org) also says it's down.

## Steps to reproduce

Go to [dephell.org](dephell.org). Or, try running the installation script:

```bash
$ curl -L dephell.org/install | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (7) Failed to connect to dephell.org port 80: Connection refused
```

**Comment by orsinium** [comment]
Wow, thank you. Something happened with my nginx. It's up now. I need a simple monitoring tool.
