### ISSUE TITLE
Function name typo

### ISSUE THREAD

**Issue by delimitry** [dephell/dephell#43]
The `analize_conflict` function should be named `analyze_conflict`.
https://github.com/dephell/dephell/blob/master/dephell/controllers/conflict.py#L43

**Comment by delimitry** [comment]
And `REX_BEGINING` should be `REX_BEGINNING`.
https://github.com/dephell/dephell/blob/master/dephell/controllers/conflict.py#L28

**Comment by orsinium** [comment]
Fixed. Please, update dephell to 0.5.8
