### ISSUE TITLE
Less dependencies

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#51]
Firstly, let's reuse `_vendor` dirs from our deps to get `appdirs`, `packaging` and `requests`. Maybe, something more.

**Comment by eli-schwartz** [comment]
Have you looked at the way pip implements vendoring? https://github.com/pypa/pip/tree/master/src/pip/_vendor

It's been well tested and is both stable and reliable. Especially, it allows unbundling the vendored dependencies and seamlessly resolving them to system versions. (This is important for distributions that have policies which don't allow or strongly discourage vendoring. It also allows those distributions to e.g. correctly handle the requests "certifi" dependency, as certifi does not respect the distribution SSL certificate store.)

**Comment by orsinium** [comment]
Pip is vendorized-first: all vendors stored in the repo, imports always from vendorized directory. It's bad way because of conflicts you mentioned, difficult dependencies tracking, monkeypatching of all runtime import system etc. DepHell will be with normal dependencies management. Vendorized version will be used only for installation via pip globally for direct usage. Maybe, I'll even put it by separated name.
