### ISSUE TITLE
Support of custom warehouse 

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#53]
Now dephell uses a new pypi api to get information about packages. A few simple manipulations will allow us to use any custom repository.

**Comment by dbanty** [comment]
A couple questions all related to each other:

1. Is this issue specific for resolving dependencies from custom repositories, or will it include supporting custom repositories in the convert commands (e.g. adding an —extra-index-url when converting to requirements.txt)?
2. For this second case (supporting custom repos in convert) do you have a plan for including credentials?  There are a lot of different cases here, might be difficult.

**Comment by orsinium** [comment]
1. Full support as now supported git and conda: converting, resolving, search, all commands.
2. Auth will be definitely implemented, but in a different PR, after this issue resolving.

**Comment by orsinium** [comment]
BTW, I'm already working on it in `simple-warehouse` branch.

**Comment by dbanty** [comment]
Awesome, thanks!  Can’t wait :)
