### ISSUE TITLE
dot in package name gets converted to - during convert

### ISSUE THREAD

**Issue by mpanarin** [dephell/dephell#71]
I was converting poetry project to setuppy and pip. On both, dependency with a dot in name (ex. `ruamel.yaml`) have its dot replaced by `-`. Which is wrong for further installations

**Comment by orsinium** [comment]
Why it's wrong for installation? This is [standard python package name normalization](https://github.com/pypa/packaging/blob/master/packaging/utils.py#L14) that performed by pip, poetry etc. DepHell just makes it explicit. PyPI correctly understand it: [pypi.org/project/ruamel-yaml](https://pypi.org/project/ruamel-yaml)

**Comment by mpanarin** [comment]
Probably I worded it weirdly.
The issue I am having is this:
I installed `ruamel.yaml` via poetry with dot.
created `setup.py` with `dephell` 
after that install everything with `poetry install`
and the app doesn't work after that throwing an exception:
```
pkg_resources.DistributionNotFound: The 'ruamel-yaml==0.*,>=0.15.94' distribution was not found and is required by my_app
```

Which is fair, as it was installed as `ruamel.yaml`. If I change `-` to `.` in `setup.py` everything works as expected.

**Comment by orsinium** [comment]
```bash
$ pip3 install --user "ruamel-yaml==0.*,>=0.15.94"
Collecting ruamel-yaml==0.*,>=0.15.94
  Using cached https://files.pythonhosted.org/packages/3b/74/4491ff49198da5f9059f6ce0e71449f4798226323318661b152ef9074d79/ruamel.yaml-0.15.94-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: ruamel-yaml
Successfully installed ruamel-yaml
```

Hmm... Maybe, something wrong with poetry? I will check it.

**Comment by orsinium** [comment]
That's strange

**Comment by orsinium** [comment]
Yeah, I've reproduced it:

```bash
$ python3 setup.py install
...
Installed /usr/local/lib/python3.6/dist-packages/sampleproject-1.2.0-py3.6.egg
Processing dependencies for sampleproject==1.2.0
Searching for ruamel-yaml==0.*,>=0.15.94
Reading https://pypi.org/simple/ruamel-yaml/
No local packages or working download links found for ruamel-yaml==0.*,>=0.15.94
error: Could not find suitable distribution for Requirement.parse('ruamel-yaml==0.*,>=0.15.94')
```

It's bug in setuptools. I will fix it :)

**Comment by mpanarin** [comment]
Awesome, thanks!

**Comment by orsinium** [comment]
NB:
1. update name from PyPI API if new name contains dot
1. use `raw_name` for setup.py

**Comment by orsinium** [comment]
As temporary solution you can use pip instead of setuptools:

```
python3 -m pip install .
```

**Comment by orsinium** [comment]
Fix in master. I will let you know when it is released on PyPI :)

**Comment by orsinium** [comment]
Released. Please, update dephell to 0.7.1.
