### ISSUE TITLE
More examples for `deps convert` command 

### ISSUE THREAD

**Issue by cclauss** [dephell/dephell#72]
https://github.com/dephell/dephell/blob/master/docs/cmd-deps-convert.md gives lots of examples but not one of the form:
```
dephell deps convert --from=requirements.txt --to=pyproject.toml
```

**Comment by orsinium** [comment]
What is this issue about? Documentation is not clear that you can convert anything to anything? Or this command doesn't work for you? Please, describe it, and I will fix it anyway :)

**Comment by cclauss** [comment]
Docs not clear.  Sorry for not being clear myself.  My sense is that a lot of folks will want to jump from legacy __requirements.txt__ straight to __pyproject.toml__ so documenting that conversion will help.

**Comment by orsinium** [comment]
Cool, got it.

**Comment by orsinium** [comment]
Fixed. Thank you for issue :)
