### ISSUE TITLE
Docs: "Edit on GitHub" returns 404 error

### ISSUE THREAD

**Issue by cclauss** [dephell/dephell#74]
https://dephell.readthedocs.io and click "__Edit on GitHub__" --> 404 error

**Comment by orsinium** [comment]
Ugh, sphinx substitutes `/origin/` in URL. That's strange. Thank you, I'll dig in it.

**Comment by orsinium** [comment]
Fixed in settings of project on readthedocs.org. See https://github.com/rtfd/readthedocs.org/issues/5518
