### ISSUE TITLE
Specify owner name for `generate license` command

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#87]
```bash
dephell generate license --owner="My Cool Team" MIT
```

**Comment by nandahkrishna** [comment]
I'd like to work on this issue if possible. Do I just have to add another argument to the parser for owner?

**Comment by orsinium** [comment]
In `get_parser` in `GenerateLicenseCommand`, `config/builders.py`, `config/scheme.py`, and replace `name=getuser().title()` on `name=config.get('owner') or getuser().title()`. Much places, but I believe in you :)

**Comment by nandahkrishna** [comment]
Alright, thanks :)

**Comment by orsinium** [comment]
Oh, if you add it in `config/builders.py` in `build_other` you don't need to add it in `get_parser`. One less step ^^"

**Comment by nandahkrishna** [comment]
Oh okay, got it.

**Comment by nandahkrishna** [comment]
This issue can be closed right?

**Comment by orsinium** [comment]
Sure. Thank you :) Just type "Close #87" instead of "Fixes issue #87" in the description of PR, and Github will close it automatically.

**Comment by nandahkrishna** [comment]
Ah, thanks!
