### ISSUE TITLE
`inspect project` command

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#90]
Read `from` and show json of `attr.asdict(root)`

**Comment by jaibhageria** [comment]
@orsinium I would like to work on the issue. Can you please elaborate and explain what is to be done?

**Comment by orsinium** [comment]
Sure.

```
        loader = CONVERTERS[self.config['from']['format']]
        loader = loader.copy(project_path=Path(self.config['project']))
        root = loader.load(path=self.config['from']['path'])
```

Do a command with it and have a look at `root`. It contains information about the project. Make a nice dict with info from it and print result:

```
        print(make_json(
            data=data,
            key=self.config.get('filter'),
            colors=not self.config['nocolors'],
            table=self.config['table'],
        ))
        return True
```

Also, `attr.asdict` can help to make the dict. Have fun!

**Comment by jaibhageria** [comment]
Thanks! I will start working on it now.

**Comment by jaibhageria** [comment]
I encountered some non-serialisable JSON objects while trying to pretty print the json output of attr.asdict(root). 
Some of those are :
* 'constraints' : Constraint()
* 'marker': MarkerTracer()

What do you suggest has to be done with this?

**Comment by orsinium** [comment]
Where are they located? If in `dependencies`, just don't dump `dependencies` at all, we don't need such mess in output. If somewhere else, they can be converted to `str(...)`.

**Comment by jaibhageria** [comment]
Okay, cool.
Which keys do you want to be printed for output of `inspect project` ?

**Comment by orsinium** [comment]
Have a look what's important, I trust you.

**Comment by jaibhageria** [comment]
@orsinium can you have a look at the PR I have opened addressing this issue?
